version: '3.7'

services:

  frontend:
    container_name: misaludrenal_frontend
    image: nginx:1.17.1-alpine
    working_dir: /usr/local/app
    volumes:
      - type: bind
        source: /var2/dockers-studentsprojects-deploy-0/DialisisPeritonealDeploy/my-nginx-frontend.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: /var2/dockers-studentsprojects-deploy-0/DialisisPeritonealDeploy/frontend/
        target: /usr/share/nginx/html
    ports:
      - 8103:80

  backend:
    container_name: misaludrenal_backend
    image: openjdk:19
    working_dir: /code
    ports:
      - 8104:8081
    environment:
      - DATABASE_URL=jdbc:mysql://10.128.0.15:3306/db01student1151788?useSSL=false&serverTimezone=UTC
      - DATABASE_USERNAME=student1151788
      - DATABASE_PASSWORD=matildealexandraal@ufps.edu.co
    volumes:
      - type: bind  
        source: /var2/dockers-studentsprojects-deploy-0/DialisisPeritonealDeploy/backend/target
        target: /code
    command: java -jar /code/DialisisPeritoneal-0.0.1-SNAPSHOT.war
